## Homepage
title = "Hinode"
titleSeparator = "-"
titleAddition = "Clean Blog Theme"
description = "Hinode is a clean blog theme for your Hugo site based on Bootstrap 5."
fullCover = false
fixedNav = true
mainSections = ["blog", "projects"]
docs_version = "0.8"

## Open Graph
images = ["logo.png"]
ogLocale = "en_US"
domainTLD = "hinode-demo.markdumay.org"

## Twitter Cards
# twitterSite = "@gethinode"
# twitterCreator = "@markdumay"

## JSON-LD
schemaType = "Organization"
schemaName = "Hinode"
schemaAuthor = "Mark Dumay"
schemaAuthorTwitter = "https://twitter.com/markdumay"
schemaAuthorLinkedIn = "https://www.linkedin.com/in/markdumay/"
schemaAuthorGitHub = "https://github.com/markdumay"
schemaLocale = "en-US"
schemaLogo = "img/logo512x512.png"
schemaLogoWidth = 512
schemaLogoHeight = 512
schemaImage = "img/logo1280x640.png"
schemaImageWidth = 1280
schemaImageHeight = 640
# schemaTwitter = "https://twitter.com/gethinode"
# schemaLinkedIn = ""
schemaGitHub = "https://github.com/markdumay/hugo-theme-hinode"
schemaSection = "blog"


[favicon]
    logo = "img/favicon.png"
    sizes = [16, 32, 48]

[search]
    enabled = true

[toc]
    enabled = true

[style]
    themeOpacity = "10"
    themeFont = "Inter"
    themeFontPath = "https://fonts.googleapis.com/css2?family=Inter:wght@200;300;600&display=swap"
    primary = "#D43900"
    secondary = "#6c757d"
    success = "#198754"
    info = "#0dcaf0"
    warning = "#ffc107"
    danger = "#dc3545"
    light = "#f8f9fa"
    dark = "#212529"

[main]
    featurePhoto = "/img/sunrise.jpg" # source: https://unsplash.com/photos/ZX6BPboJrYk
    logo = "/img/logo_embedded.svg"

[comments]
    enabled = false
    repo = "" # Replace with your repository.
    #issueTerm = "pathname" # pathname, url, title, og:title
    #label = "comment"
    # By default, light and dark mode correspond to github-light and github-dark, respectively.
    # Optional values: github-light, github-dark, preferred-color-scheme, github-dark-orange, icy-dark, dark-blue, photon-dark.
    #theme = "" 

[links]
    bootstrap = "https://getbootstrap.com"
    bs_badge_heading = "https://getbootstrap.com/docs/5.2/components/badge/#headings"
    cc_by_nc_4_0 = "https://creativecommons.org/licenses/by-nc/4.0/"
    commit_message = "https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html"
    contrast_checker = "https://accessibleweb.com/color-contrast-checker/"
    css_codeguide = "https://codeguide.co/#css"
    eslint = "https://eslint.org"
    flexsearch = "https://github.com/nextapps-de/flexsearch"
    git_download = "https://git-scm.com"
    github_pr = "https://help.github.com/articles/about-pull-requests/"
    github_rebase = "https://help.github.com/articles/about-git-rebase/"
    html_codeguide = "https://codeguide.co/#html"
    hugo = "https://gohugo.io"
    hugo_imaging = "https://gohugo.io/content-management/image-processing/#imaging-configuration"
    issue_tracker = "https://github.com/markdumay/hugo-theme-hinode/issues"
    license = "https://github.com/markdumay/hugo-theme-hinode/blob/main/LICENSE"
    markdown_md013 = "https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md013---line-length"
    markdown_md024 = "https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md024---multiple-headings-with-the-same-content"
    markdown_md026 = "https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md026---trailing-punctuation-in-heading"
    markdown_md033 = "https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md033---inline-html"
    markdown_md034 = "https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md034---bare-url-used"
    markdown_md051 = "https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md051---link-fragments-should-be-valid"
    markdown_md053 = "https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md053---link-and-image-reference-definitions-should-be-needed"
    markdown_rules = "https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md"
    markdownlint = "https://github.com/DavidAnson/markdownlint-cli2"
    mozilla_image = "https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images"
    netlify = "https://www.netlify.com"
    nodejs = "https://nodejs.org"
    npm = "https://www.npmjs.com"
    observatory = "https://observatory.mozilla.org/analyze/hinode-demo.markdumay.org"
    pagespeed = "https://pagespeed.web.dev/report?url=https%3A%2F%2Fhinode-demo.markdumay.org%2F"
    repository = "https://github.com/markdumay/hugo-theme-hinode"
    repository_child = "https://github.com/markdumay/hugo-theme-hinode-child.git"
    stylelint = "https://stylelint.io"
    utterances = "https://utteranc.es"
    wcag_contrast = "https://www.w3.org/TR/WCAG20/#visual-audio-contrast"