[search]
    enabled = true

[style]
    themeColor = "#00b0f0"
    themeOpacity = "25"

[comments]
    # enabled = false
    enabled = true
    repo = "razonyang/hugo-theme-bootstrap-comments" # Replace with your repository.
    #issueTerm = "pathname" # pathname, url, title, og:title
    #label = "comment"
    # By default, light and dark mode correspond to github-light and github-dark, respectively.
    # Optional values: github-light, github-dark, preferred-color-scheme, github-dark-orange, icy-dark, dark-blue, photon-dark.
    #theme = "" 
