name = "Hinode"
license = "MIT"
licenselink = "https://github.com/markdumay/hugo-theme-hinode/blob/main/LICENSE"
description = "A clean blog theme for your Hugo site based on Bootstrap 5."
homepage = "https://github.com/markdumay/hugo-theme-hinode"
demosite = "https://hinode.netlify.app"
tags = ["blog", "minimal", "modern", "customizable", "search", "bootstrap"]
features = ["bootstrap framework", "full text search", "page layouts"]
min_version = "0.81.0"

[author]
  name = "Mark Dumay"
  homepage = "https://github.com/markdumay"

# If porting an existing theme
[original]
  name = "Blist"
  homepage = "https://apvarun.com"
  repo = "https://github.com/apvarun/blist-hugo-theme"
