baseURL = "https://hugo-hinode-demo.markdumay.org/"
title = "Hinode"
author = "Mark Dumay"
copyright = "Copyright © 2022 Mark Dumay."
paginate = 9
languageCode = "en-us"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]
theme = "hugo-theme-hinode"
themesDir = "../.."
enableEmoji = true

mainSections = ["blog", "projects"]

[params]
  license = "Licensed under Creative Commons (<a href='https://creativecommons.org/licenses/by-nc-sa/4.0/' class='link-secondary' target='_blank'>CC BY-NC-SA 4.0</a>)."
  offlineSearch = true


[params.homepage.social]
  # Global params xommon for both languages
  title = "Follow me"
  description = "I work on everything coding and tweet developer memes"
  twitter = "https://twitter.com/"
  linkedin = "https://linkedin.com/in/"
  github = "https://github.com/"
  medium = "https://medium.com/"
  reddit = "https://reddit.com/"
  dribbble = "https://dribbble.com/"


[languages]
  [languages.en]
    # contentDir = "content/en" #English
    # weight = 1
    # languageName = "English"
    [languages.en.params]
      introTitle = "Hey! I'm Katheryn Fox"
      introSubtitle = "26 y/o junior developer who enjoys social card games, blogging and painting"
      introPhoto = "/picture.jpg"
      logo = "/blist-logo.png"


[menu]

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 10

  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 20

  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 30

[taxonomies]
  tag = 'tags'

[privacy]
  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true

# syntax highlight settings
# [markup]
#   [markup.highlight]
#     style = "dracula"
#   [markup.goldmark.renderer]
#     # Enable to include inline HTML
#     unsafe = true


[highlight]
  anchorLineNos = false
  codeFences = true
  guessSyntax = true
  hl_Lines = ""
  lineAnchors = ""
  lineNoStart = 1
  lineNos = true
  lineNumbersInTable = false
  noClasses = false
  # style = "monokai" # This parameter affects nothing, see https://github.com/razonyang/hugo-theme-bootstrap#syntax-highlighting.
  tabWidth = 2

[goldmark]
[goldmark.extensions]
definitionList = true
footnote = true
linkify = true
strikethrough = true
table = true
taskList = true
typographer = true

[goldmark.parser]
autoHeadingID = true
autoHeadingIDType = 'github'
[markup.goldmark.parser.attribute]
block = true

[goldmark.renderer]
hardWraps = false
unsafe = true
xhtml = false
